# Generated by Django 5.1.7 on 2025-03-09 19:14

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_retailer_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="retailer",
            managers=[
                ("objects", api.models.RetailerManager()),
            ],
        ),
    ]
